### ISSUE TITLE
YouTube timeouts

### ISSUE THREAD

**Issue by DRSchlaubi** [lavalink-devs/youtube-source#23]
Not sure if this is related to #14, since it started happening to me shortly after that, but connections to YouTube now start to timeout

<details><summary>Stacktrace</summary>
<p>

```
lavalink-1  | 2024-06-29T20:35:17.477Z ERROR 1 --- [back-1-thread-3] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of VkMhCyywxa4
lavalink-1  | 
lavalink-1  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
lavalink-1  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
lavalink-1  |   at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
lavalink-1  | Caused by: java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to www.youtube.com:443 [www.youtube.com/2a00:1450:4001:812:0:0:0:200e] failed: Connect timed out
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.cipher.SignatureCipherManager.getPlayerScript(SignatureCipherManager.java:159) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.cipher.SignatureCipherManager.getCachedPlayerScript(SignatureCipherManager.java:168) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:73) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.clients.skeleton.ThumbnailStreamingNonMusicClient.loadFormats(ThumbnailStreamingNonMusicClient.java:35) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   ... 4 common frames omitted
lavalink-1  | Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to www.youtube.com:443 [www.youtube.com/2a00:1450:4001:812:0:0:0:200e] failed: Connect timed out
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:150) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:69) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.http.SimpleHttpClientConnectionManager.connect(SimpleHttpClientConnectionManager.java:87) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:73) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   at dev.lavalink.youtube.cipher.SignatureCipherManager.getPlayerScript(SignatureCipherManager.java:147) ~[youtube-plugin-1.1.0.jar!/:na]
lavalink-1  |   ... 11 common frames omitted
lavalink-1  |   Suppressed: com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator$AdditionalDetails: Encountered when opening a connection with the following details:
lavalink-1  |   host: https://www.youtube.com:443
lavalink-1  |   localAddress: /[2a02:c207:3002:3203:0:d1f9:ffce:730f]:0
lavalink-1  |   remoteAddress: www.youtube.com/[2a00:1450:4001:812:0:0:0:200e]:443
lavalink-1  |   connectTimeout: 3000
lavalink-1  |   triedAddresses: www.youtube.com/2a00:1450:4001:812:0:0:0:200e
lavalink-1  | Caused by: java.net.SocketTimeoutException: Connect timed out
lavalink-1  |   at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551) ~[na:na]
lavalink-1  |   at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[na:na]
lavalink-1  |   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
lavalink-1  |   at java.base/java.net.Socket.connect(Socket.java:639) ~[na:na]
lavalink-1  |   at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[httpclient-4.5.14.jar!/:4.5.14]
lavalink-1  |   at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:145) ~[lavaplayer-2.2.0.jar!/:na]
lavalink-1  |   ... 22 common frames omitted
lavalink-1  | 
lavalink-1  | 2024-06-29T20:35:17.513Z  I
```

</p>
</details>

**Comment by devoxin** [comment]
What clients are you using? Are you sure this isn't a network problem?

**Comment by DRSchlaubi** [comment]
It was a networking problem https://github.com/lavalink-devs/Lavalink/pull/1061
