### ISSUE TITLE
Getting Error: Something broke when playing the track.

### ISSUE THREAD

**Issue by Root-Time** [lavalink-devs/youtube-source#29]
When i use Spotify Link or YouTube Link the Lavalink breaks.

2 days ago it worked absolutely fine.

This is the Error:
```yaml
2024-07-09T17:38:35.615Z  INFO 1310718 --- [Lavalink] [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/6fxeXlCSt4WLVlbqxgUBMB?si=1407caf08c404d6e"
2024-07-09T17:38:35.903Z  INFO 1310718 --- [Lavalink] [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded track Funk of Galáctico
2024-07-09T17:38:35.934Z  INFO 1310718 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F6fxeXlCSt4WLVlbqxgUBMB%3Fsi%3D1407caf08c404d6e
2024-07-09T17:38:36.370Z  INFO 1310718 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/1bnyib2uak72irop/players/1009761004214833213, payload={"voice":{"sessionId":"4d905e798b333dffcd28f76c107c073a","endpoint":"frankfurt1656.discord.media:443","token":"f254a675c7e2c3d8"}}
2024-07-09T17:38:36.636Z  INFO 1310718 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/1bnyib2uak72irop/players/1009761004214833213, payload={"track":{"encoded":"QAACDwMAEkZ1bmsgb2YgR2Fsw6FjdGljbwAEU1hJRAAAAAAAAWFdABY2ZnhlWGxDU3Q0V0xWbGJxeGdVQk1CAAEANWh0dHBzOi8vb3Blbi5zcG90aWZ5LmNvbS90cmFjay82ZnhlWGxDU3Q0V0xWbGJxeGdVQk1CAQBAaHR0cHM6Ly9pLnNjZG4uY28vaW1hZ2UvYWI2NzYxNmQwMDAwYjI3MzFmYmJkNWZjNGRkNDRhODVkNzNjZjQ2MgEADFVLWkdDMjQwMjc5MgAHc3BvdGlmeQEAEkZ1bmsgb2YgR2Fsw6FjdGljbwEANWh0dHBzOi8vb3Blbi5zcG90aWZ5LmNvbS9hbGJ1bS8wY3BmZ0R6akhadVlmaUJjN2pQc242AQA2aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tL2FydGlzdC8zZVR5N3l2UkhucFBLWTRoTkNmWVlYAQBAaHR0cHM6Ly9pLnNjZG4uY28vaW1hZ2UvYWI2NzYxNjEwMDAwZTVlYmQwNWNmYTJiYWI3YzYxMjBlNDRiMDNlZAEAa2h0dHBzOi8vcC5zY2RuLmNvL21wMy1wcmV2aWV3LzI2YTQxZDhmMjhiNjViNTY5ZmUxM2IxNGUxZmQyMzY0NjY1ODFkMzI/Y2lkPTVlYWRmZjY3ZDUxYjQ5Zjc5MzQwNzI3MWE1NDQ5OWUwAAAAAAAAAAAA"},"volume":40}
2024-07-09T17:38:37.323Z ERROR 1310718 --- [Lavalink] [back-1-thread-1] d.l.y.cipher.SignatureCipherManager      : Problematic YouTube player script /s/player/b22ef6e7/player_ias.vflset/nl_NL/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script10231037904179618257.js
2024-07-09T17:38:37.968Z ERROR 1310718 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 6fxeXlCSt4WLVlbqxgUBMB

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-2.2.1.jar!/:na]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[na:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.1.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[youtube-plugin-1.3.0.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[youtube-plugin-1.3.0.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[youtube-plugin-1.3.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.1.jar!/:na]
        at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:55) ~[lavasrc-plugin-4.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.1.jar!/:na]
        ... 4 common frames omitted

2024-07-09T17:38:37.983Z  INFO 1310718 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/1bnyib2uak72irop/players/1009761004214833213, payload={"track":{"encoded":null}}
```

**Comment by devoxin** [comment]
Full debug logs along with your configuration please.

**Comment by Root-Time** [comment]
Fixed by updating YouTube Lavalink Extension.

**Comment by topi314** [comment]
not sure where this comment went from @Root-Time, but they closed with following commnet:
> Fixed by updating YouTube Lavalink Extension.

**Comment by U-M9** [comment]
fixed it, i compiled the player myself and it fixed the issue

**Comment by lolcat-y** [comment]
I'm having the same issue but I'm not sure how do I updating YouTube-Lavlink Buy this do you mean update the plugin If so this is a plug-in that I'm using to play music youtube-plugin-1.3.0.jarAnd I'm getting the same issue When i use Spotify Link or YouTube Link the Lavalink breaks.

2 days ago it worked absolutely fine.

**Comment by devoxin** [comment]
> Buy this do you mean update the plugin

yes

> youtube-plugin-1.3.0.jar

use 1.4.0

> When i use Spotify Link

doesn't matter, spotify mirrors to whatever you tell it to which is typically youtube

> 2 days ago it worked absolutely fine.

irrelevant, things break all the time because that's the nature of scraping. this is useless information

**Comment by lolcat-y** [comment]
> 1.4.0

Hey man are you able to show me a link where I could get the updated version of youtube-plugin-1.3.0.jar

**Comment by topi314** [comment]
https://github.com/lavalink-devs/youtube-source/#plugin

**Comment by devoxin** [comment]
The jar or the dependency itself? because you can just add it to your `plugins` block within your `application.yml` and Lavalink will fetch the jar automatically

**Comment by lolcat-y** [comment]
> https://github.com/lavalink-devs/youtube-source/#plugin

omg thxxxxx

**Comment by lolcat-y** [comment]
> The jar or the dependency itself? because you can just add it to your `plugins` block within your `application.yml` and Lavalink will fetch the jar automatically  


This is what my coffee currently looks like 



server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "autocreativeco"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
      spotify:
        enabled: true
        clientId: "f8fc9a16ad3440dfa5a7aeaab5f298ce"
        clientSecret: "311dd4092d6d4a8b8c9203a293f24cd4"
        market: "US"
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

plugins:
  youtube:  
    enabled: true
    name: sam
    allowSearch: true
    allowDirectVideoIds: true 
    allowDirectPlaylistIds: true


metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  level:
    # Set this to DEBUG to enable more detailed logging. Please note that this will log probably spam your console.
    root: INFO
    # Set this to DEBUG to enable more detailed logging from Lavalink
    lavalink: DEBUG
    # Set this to TRACE to see all WebSocket messages
    lavalink.server.io.SocketContext: TRACE
    # Log all track exceptions (COMMON, SUSPICIOUS & FAULT)
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG

  # This will log all requests to the REST API
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true

**Comment by devoxin** [comment]
Read the documentation on how to configure your Lavalink nodes.
