### ISSUE TITLE
403 error code from Youtube links

### ISSUE THREAD

**Issue by OmarEfat** [lavalink-devs/youtube-source#41]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [x] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.5.1 YoutubeAudioSourceManager youtube = new YoutubeAudioSourceManager(/allowSearch:/ true,                 new Client[]{new MusicWithThumbnail(), new WebWithThumbnail(), new TvHtml5Embedded()});

### The search query, URL, playlist or video ID that triggered the issue

N/A

### Code Example

N/A

### Exception and Stacktrace

16:00:32.081 lava-daemon-pool-playback-1-thread            LocalAudioTrack ERROR  Error in playback of G7KNmW9a75Y
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Not success status code: 403
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
    at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
    at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148)
    at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116)
    at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)

**Comment by Nansess** [comment]
i have noticed this as well, are you currently on the latest version of youtube source (1.5.1)?

**Comment by devoxin** [comment]
Can you try enable more clients?

**Comment by OmarEfat** [comment]
> i have noticed this as well, are you currently on the latest version of youtube source (1.5.1)?

Yes

**Comment by OmarEfat** [comment]
> Can you try enable more clients?

@devoxin  sorry what you mean by "more clients"?

**Comment by devoxin** [comment]
> > Can you try enable more clients?
> 
> @devoxin sorry what you mean by "more clients"?

https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients

**Comment by baskwo** [comment]
I updated to 1.5.2 and still happening. I have WEB and WEB_REMIX.
Do you want me to try another client? If so which one?

**Comment by devoxin** [comment]
Can you show me how you're registering the youtube source manager?

**Comment by baskwo** [comment]
within application.yaml
`lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.5.2"
      repository: "https://maven.lavalink.dev/releases"
      `
      
      I don't know how to do a good formatting sadly on github :)

**Comment by devoxin** [comment]
Ah I assumed you were using Lavaplayer directly based on the code snippet in your first post.
You can try add more clients, yes. If you're only using `TvHtml5Embedded` and `WEB` (`MUSIC` is not used for playback) you run a higher risk of getting 403s.

**Comment by baskwo** [comment]
What client do you recommend to use?

**Comment by devoxin** [comment]
None specifically. It all depends on your requirements. Have a read of https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients and pick the ones that suit your requirements the best.

**Comment by baskwo** [comment]
Okey, I added `TVHTML5EMBEDDED` and `ANDROID_MUSIC` and it works now.
Why would WEB get a 403? Rate limited?

**Comment by devoxin** [comment]
Sometimes it happens with no clear explanation as to why, but the idea is that enabling more clients offers more resilience against these 'edge cases'.

**Comment by baskwo** [comment]
Interesting! I might look up the stacktrace and try to see if I see something :)
Thank you!

**Comment by OmarEfat** [comment]
We updated to 1.5.2 and now working, thanks
