### ISSUE TITLE
Not success status code: 403 when playing from YouTube

### ISSUE THREAD

**Issue by hirusha-adi** [lavalink-devs/youtube-source#45]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [x] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.7.2

### The search query, URL, playlist or video ID that triggered the issue

song name here

### Code Example

Note that everything worked until 3rd of September.

Lavalink version: `4.0.7`

This is used in a discord bot (based on [Pomice](https://github.com/cloudwithax/pomice)). I use the latest version of Pomice: `v2.9.1`

The music command of the bot can be found [here](https://github.com/hirusha-adi/Near/blob/main/near/cogs/musicplayer.py).

It runs in a docker container (has a datacenter IP)

`application.yml`

- tried both with and without the proxy, doesnt work
- tried with another youtube account, doesnt work

```yml
# config for lavalink, put this file in the folder with Lavalink.jar
server:
  port: 2333
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    youtubeConfig:
      email: ""
      password: ""
#  httpConfig:
#    proxyHost: ""
#    proxyPort: 
#    proxyUser: ""
#    proxyPassword: ""
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      snapshot: false
    # youtube:
    #   enabled: true
    #   allowSearch: true
    #   allowDirectVideoIds: true
    #   allowDirectPlaylistIds: true
    #   clients:
    #     - MUSIC
    #     - ANDROID
    #     - WEB
    #   WEB:
    #     playback: true
    #   TVHTML5EMBEDDED:
    #     playlistLoading: true
    #     videoLoading: true
    #     searching: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/
  level:
    root: INFO
    lavalink: DEBUG
#    lavalink.server.io.SocketContext: TRACE
#    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG
```

### Exception and Stacktrace

```
2024-09-04T06:38:42.989Z  INFO 1 --- [Lavalink] [           main] o.s.boot.SpringApplication               :   .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.3.0)
2024-09-04T06:38:43.095Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : Starting Launcher v4.0.7 using Java 23 with PID 1 (/lavalink/Lavalink.jar started by root in /lavalink)
2024-09-04T06:38:43.095Z DEBUG 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : Running with Spring Boot v3.3.0, Spring v6.1.9
2024-09-04T06:38:43.096Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-09-04T06:38:44.691Z  INFO 1 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Downloading https://maven.lavalink.dev/releases/dev/lavalink/youtube/youtube-plugin/1.7.2/youtube-plugin-1.7.2.jar
2024-09-04T06:38:45.813Z  INFO 1 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Loaded youtube-plugin-1.7.2.jar (15 classes)
2024-09-04T06:38:46.080Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : Started Launcher in 3.756 seconds (process running for 4.799)
2024-09-04T06:38:46.155Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : 
       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/
	Version:        4.0.7
	Build time:     08.07.2024 22:14:17 UTC
	Branch          HEAD
	Commit:         93102f8
	Commit time:    08.07.2024 21:49:02 UTC
	JVM:            23
	Lavaplayer      2.2.1
2024-09-04T06:38:46.161Z  INFO 1 --- [Lavalink] [           main] o.s.boot.SpringApplication               :   .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.3.0)
2024-09-04T06:38:46.173Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-09-04T06:38:47.310Z  WARN 1 --- [Lavalink] [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2024-09-04T06:38:47.339Z  INFO 1 --- [Lavalink] [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2024-09-04T06:38:47.341Z  INFO 1 --- [Lavalink] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1161 ms
2024-09-04T06:38:47.918Z DEBUG 1 --- [Lavalink] [           main] l.s.config.AudioPlayerConfiguration      : No rate limit config block found, skipping setup of route planner
2024-09-04T06:38:47.967Z  INFO 1 --- [Lavalink] [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2024-09-04T06:38:48.344Z  WARN 1 --- [Lavalink] [           main] d.l.youtube.plugin.YoutubePluginLoader   : youtubeConfig missing or 'clients' was not specified, default values will be used.
2024-09-04T06:38:48.403Z  INFO 1 --- [Lavalink] [           main] d.l.youtube.plugin.YoutubePluginLoader   : YouTube source initialised with clients: WEB_REMIX, WEB, ANDROID_TESTSUITE, TVHTML5_SIMPLY_EMBEDDED_PLAYER 
2024-09-04T06:38:48.644Z  INFO 1 --- [Lavalink] [           main] l.server.config.KoeConfiguration         : OS: LINUX, Arch: X86_64
2024-09-04T06:38:48.644Z  INFO 1 --- [Lavalink] [           main] l.server.config.KoeConfiguration         : Enabling JDA-NAS
2024-09-04T06:38:48.651Z  INFO 1 --- [Lavalink] [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2024-09-04T06:38:48.660Z  INFO 1 --- [Lavalink] [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2024-09-04T06:38:48.739Z  WARN 1 --- [Lavalink] [           main] l.server.config.SentryConfiguration      : Turning off sentry
2024-09-04T06:38:49.279Z DEBUG 1 --- [Lavalink] [           main] l.server.io.RequestLoggingFilter         : Filter 'logFilter' configured for use
2024-09-04T06:38:49.284Z DEBUG 1 --- [Lavalink] [           main] l.server.io.ResponseHeaderFilter         : Filter 'responseHeaderFilter' configured for use
2024-09-04T06:38:49.289Z  INFO 1 --- [Lavalink] [           main] io.undertow                              : starting server: Undertow - 2.3.13.Final
2024-09-04T06:38:49.306Z  INFO 1 --- [Lavalink] [           main] org.xnio                                 : XNIO version 3.8.8.Final
2024-09-04T06:38:49.318Z  INFO 1 --- [Lavalink] [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.8.Final
2024-09-04T06:38:49.480Z  INFO 1 --- [Lavalink] [           main] org.jboss.threads                        : JBoss Threads version 3.5.0.Final
2024-09-04T06:38:49.554Z  INFO 1 --- [Lavalink] [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port 2333 (http) with context path '/'
2024-09-04T06:38:49.565Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : Started Launcher in 3.476 seconds (process running for 8.284)
2024-09-04T06:38:49.566Z  INFO 1 --- [Lavalink] [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2024-09-04T06:38:56.016Z  INFO 1 --- [Lavalink] [  XNIO-1 task-2] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-09-04T06:38:56.016Z  INFO 1 --- [Lavalink] [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-09-04T06:38:56.019Z  INFO 1 --- [Lavalink] [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
2024-09-04T06:38:56.227Z  INFO 1 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
2024-09-04T06:38:56.235Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /172.18.0.3:44158
2024-09-04T06:38:56.287Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/websocket
2024-09-04T06:38:56.427Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] lavalink.server.io.SocketServer          : Connection successfully established from Pomice/2.9.1
2024-09-04T06:39:06.933Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:song name here"
2024-09-04T06:39:07.919Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: song name here
2024-09-04T06:39:08.083Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch:song%20name%20here
2024-09-04T06:39:08.180Z  INFO 1 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/9i4osld6kqaptis6/players/953475156309856256?noReplace=False, payload={"encodedTrack": "QAAAuwMAIkFsZXNzaWEgQ2FyYSAtIEhlcmUgKEx1Y2lhbiBSZW1peCkAC1RyYXAgTmF0aW9uAAAAAAADLIAAC0RBcnpaM1J2ZWpVAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9REFyelozUnZlalUBADBodHRwczovL2kueXRpbWcuY29tL3ZpL0RBcnpaM1J2ZWpVL21xZGVmYXVsdC5qcGcAAAd5b3V0dWJlAAAAAAAAAAA=", "position": "0", "endTime": null}
2024-09-04T06:39:08.515Z  INFO 1 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/9i4osld6kqaptis6/players/953475156309856256, payload={"voice": {"token": "37a4d6750a6ac9c4", "endpoint": "singapore11053.discord.media:443", "sessionId": "e95c93638460464b82730ba6510276f2"}}
2024-09-04T06:39:08.769Z  INFO 1 --- [Lavalink] [back-1-thread-1] d.l.y.http.YoutubeAccessTokenTracker     : Updating YouTube visitor id succeeded, new one is CgtScV9vZnR2Q0JaUSiMgeC2BjIKCgJHQhIEGgAgSzoMCAEgrq-YycWRgOxm, next update will be after 600 seconds.
2024-09-04T06:39:09.112Z ERROR 1 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of DArzZ3RvejU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.1.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-2.2.1.jar!/:na]
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[na:na]
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-2.2.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.1.jar!/:na]
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:153) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:121) ~[youtube-plugin-1.7.2.jar!/:na]
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[youtube-plugin-1.7.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.1.jar!/:na]
	... 4 common frames omitted
	Suppressed: dev.lavalink.youtube.ClientInformation: 
  yts.version: 1.7.2
  client.identifier: TVHTML5_SIMPLY_EMBEDDED_PLAYER
  client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}
2024-09-04T06:39:09.412Z  INFO 1 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/9i4osld6kqaptis6/players/953475156309856256
```

detailed logs, with root logging level set to DEBUG: [click here](https://drive.google.com/file/d/1j1l5Tc6X6F7haSTgD_yzYkBWlrQa8Li7/view?usp=sharing)

**Comment by topi314** [comment]
as you can see your youtube config is wrong
```
youtubeConfig missing or 'clients' was not specified, default values will be used.
```
this is not how the config is structured in the README
```yaml
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      snapshot: false
    # youtube:
    #   enabled: true
    #   allowSearch: true
    #   allowDirectVideoIds: true
    #   allowDirectPlaylistIds: true
    #   clients:
    #     - MUSIC
    #     - ANDROID
    #     - WEB
    #   WEB:
    #     playback: true
    #   TVHTML5EMBEDDED:
    #     playlistLoading: true
    #     videoLoading: true
    #     searching: true
```

you also didn't try oauth or potoken
