### ISSUE TITLE
Playing not working

### ISSUE THREAD

**Issue by MobilGame06** [lavalink-devs/youtube-source#58]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.8.3

### The search query, URL, playlist or video ID that triggered the issue

ZAt8oxY0GQo
EDnIEWyVIlE
1jT1YIoOvKk

### Code Example

N/A

### Exception and Stacktrace

2024-09-28T23:08:15.602+02:00 ERROR 27 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 1jT1YIoOvKk
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:288) ~[na:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:268) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:158) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:126) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[youtube-plugin-1.8.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        ... 4 common frames omitted
        Suppressed: dev.lavalink.youtube.ClientInformation: 
  yts.version: 1.8.3
  client.identifier: WEB
  client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}

**Comment by devoxin** [comment]
> 6 different videos i tried

This is not helpful information.

Can you provide the list of clients you are using?

**Comment by MobilGame06** [comment]
i'm using this client integrated into a discord bot https://github.com/Tomato6966/lavalink-client

**Comment by HagarJNode** [comment]
Same here, but I get this exception:

00:51:23.396 WARN  c.s.d.l.t.p.LocalAudioTrackExecutor - Suspicious exception for playback of pgPEaI0GHBI
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is not available
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)

**Comment by devoxin** [comment]
> i'm using this client integrated into a discord bot https://github.com/Tomato6966/lavalink-client

[Clients](https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients) not Lavalink client.

**Comment by HagarJNode** [comment]
This one fixed my issue https://github.com/lavalink-devs/youtube-source/issues/56#issuecomment-2379587942

**Comment by MobilGame06** [comment]
> > i'm using this client integrated into a discord bot https://github.com/Tomato6966/lavalink-client
> 
> [Clients](https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients) not Lavalink client.

sry my fault i use:
            - MUSIC
            - ANDROID_TESTSUITE
            - WEB

**Comment by MobilGame06** [comment]
this fixed it for me https://github.com/lavalink-devs/youtube-source/issues/55#issuecomment-2376165932

**Comment by devoxin** [comment]
Replace web and android testsuite. They're broken.

**Comment by LucasB25** [comment]
> Replace web and android testsuite. They're broken.

What should it be replaced with?

**Comment by devoxin** [comment]
Any? There's multiple other clients to choose from.

**Comment by devoxin** [comment]
Closing as stale.

The general consensus seems to be that you should be using as many clients as you reasonably can, with the exception of `WEB`, `ANDROID_TESTSUITE` and `ANDROID_LITE` as these appear to be completely dead.

You may still be able to use `WEB` for playlist loading and searching, so adjust your client options as necessary. If you don't know what this means, or don't know how, it's probably better if you just disable `WEB` completely. For any further queries, join the Discord linked in the README.
