### ISSUE TITLE
random 'Please sign in' error 

### ISSUE THREAD

**Issue by ZL927** [lavalink-devs/youtube-source#61]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.8.3

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

any url 

### Code Example

-

### Exception and Stacktrace

2024-10-10T17:42:06.397+08:00 WARN 15980 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor : Suspicious exception for playback of 6dOtVTDdiauQNBQEDOtlAB

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102) ~[jar:file:C:\Users\user\music.\plugins\youtube-plugin-1.8.3.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:55) ~[jar:file:C:\Users\user\music.\plugins\lavasrc-plugin-4.3.0.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]

### What is your client configuration?

WEB_REMIX, WEB, ANDROID_TESTSUITE, TVHTML5_SIMPLY_EMBEDDED_PLAYER

**Comment by YTiceice** [comment]
I also encountered this problem, how did you fix it?

**Comment by KatsuraNTR** [comment]
Same here.

**Comment by lMolMol** [comment]
same issue

**Comment by devoxin** [comment]
Use OAuth.

**Comment by Tibou-17** [comment]
> Use OAuth.

Can you show examples or give link to documentation of it please ?

And this mean it no will longer be possible to use YouTube API without authentication ?

**Comment by devoxin** [comment]
> Can you show examples or give link to documentation of it please ?

Read the README.

> > And this mean it no will longer be possible to use YouTube API without authentication ?

Probably not unless a way of streaming videos without it is found.

**Comment by ZL927** [comment]
enable oauth in application.yml

> I also encountered this problem, how did you fix it?

**Comment by YTiceice** [comment]
I fixed it, thanks!
