### ISSUE TITLE
'Please sign in' error

### ISSUE THREAD

**Issue by lMolMol** [lavalink-devs/youtube-source#64]
### Basic Troubleshooting

- [X] I have checked for similar issues, and my issue is not a duplicate. (Check closed issues as well)
- [X] I have checked for pull requests that may already address my issue.
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.
- [X] I have confirmed that my issue is reproducible with the minimum viable clients (MUSIC, WEB and TVHTML5EMBEDDED)

### Version of youtube-source

1.8.3

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

any url, For example: https://www.youtube.com/live/TdmvsQeLZPA?si=hYdZZFilX1-fhP0a

### Code Example

YoutubeAudioSourceManager youtube = new YoutubeAudioSourceManager(/*allowSearch:*/ true,
                new Client[]{new MusicWithThumbnail(), new WebWithThumbnail(), new TvHtml5Embedded()});

        audioPlayerManager.registerSourceManager(youtube);

### Exception and Stacktrace

`16:07:36.440 lava-daemon-pool-playback-1-thread            LocalAudioTrack WARN   Suspicious exception for playback of TdmvsQeLZPA
 com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
     at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:102)
     at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
     at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     at java.base/java.lang.Thread.run(Thread.java:840)
`

### What is your client configuration?

MusicWithThumbnail WebWithThumbnail TvHtml5Embedded

**Comment by devoxin** [comment]
You already commented on #61. Do not open duplicate issues.
