### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by Naiml007** [lavalink-devs/youtube-source#89]
bot
```
"  op: 'event',\n" +
  "  type: 'TrackExceptionEvent',\n" +
  "  guildId: '819884207144304640',\n" +
  '  track: {\n' +
  "    encoded: 'QAAAwwMAI0tlbmRyaWNrIExhbWFyLCBTWkEgLSBBbGwgVGhlIFN0YXJzAA5LZW5kcmljayBMYW1hcgAAAAAAA5X4AAtKUWJqUzBfWmZKMAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PUpRYmpTMF9aZkowAQA0aHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9KUWJqUzBfWmZKMC9tYXhyZXNkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==',\n" +
  '    info: {\n' +
  "      identifier: 'JQbjS0_ZfJ0',\n" +
  '      isSeekable: true,\n' +
  "      author: 'Kendrick Lamar',\n" +
  '      length: 235000,\n' +
  '      isStream: false,\n' +
  '      position: 0,\n' +
  "      title: 'Kendrick Lamar, SZA - All The Stars',\n" +
  "      uri: 'https://www.youtube.com/watch?v=JQbjS0_ZfJ0',\n" +
  "      sourceName: 'youtube',\n" +
  "      artworkUrl: 'https://i.ytimg.com/vi/JQbjS0_ZfJ0/maxresdefault.jpg',\n" +
  '      isrc: null\n' +
  '    },\n' +
  '    pluginInfo: {},\n' +
  '    userData: {}\n' +
  '  },\n' +
  '  exception: {\n' +
  "    message: 'Something broke when playing the track.',\n" +
  "    severity: 'fault',\n" +
  "    cause: 'java.lang.IllegalStateException: Must find action functions from script: /s/player/3bb1f723/player_ias.vflset/bn_BD/base.js'\n" +
```

```
=false, payload={"voice":{"token":"04951a44f93be6d0","endpoint":"singapore159.discord.media:443","sessionId":"8a6addfab86a64a951d855d4b1e91484"}}
2024-12-11T19:10:14.635Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:all the stars"
2024-12-11T19:10:15.048Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Loaded playlist Search results for: all the stars
2024-12-11T19:10:15.052Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Aall+the+stars
2024-12-11T19:10:15.145Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/78zdrk00hdmokw2w/players/819884207144304640?noReplace=false, payload={"track":{"encoded":"QAAAwwMAI0tlbmRyaWNrIExhbWFyLCBTWkEgLSBBbGwgVGhlIFN0YXJzAA5LZW5kcmljayBMYW1hcgAAAAAAA5X4AAtKUWJqUzBfWmZKMAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PUpRYmpTMF9aZkowAQA0aHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9KUWJqUzBfWmZKMC9tYXhyZXNkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==","length":235000},"replaceCurrent":false,"volume":100}
2024-12-11T19:10:15.145Z  WARN 27 --- [Lavalink] [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
2024-12-11T19:10:16.442Z ERROR 27 --- [Lavalink] [back-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/3bb1f723/player_ias.vflset/bn_BD/base.js detected (issue detected with script: no actions match). Dumped to /tmp/lavaplayer-yt-player-script3889384823598138228.js
2024-12-11T19:10:16.771Z ERROR 27 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of JQbjS0_ZfJ0
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/3bb1f723/player_ias.vflset/bn_BD/base.js
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:216) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:167) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:204) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        ... 4 common frames omitted
2024-12-11T19:10:16.797Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/78zdrk00hdmokw2w/players/819884207144304640
```

**Comment by topi314** [comment]
follow the issue template
