### ISSUE TITLE
lavalink youtube playback error

### ISSUE THREAD

**Issue by Naiml007** [lavalink-devs/youtube-source#90]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.8.3

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

ytmsearch

### Code Example

N/A

### Exception and Stacktrace

```
2024-12-14T20:01:45.241Z | INFO      | CLUSTER_0 | TrackStart                   | Track Started in @ Banshai Support Server / 1315007919527559300
2024-12-14T20:01:45.869Z | ERROR     | CLUSTER_0 | PlayerException              | 'Player get exception \n' +
  "  op: 'event',\n" +
  "  type: 'TrackExceptionEvent',\n" +
  "  guildId: '1315007919527559300',\n" +
  '  track: {\n' +
  "    encoded: 'QAAAvwMAI0tlbmRyaWNrIExhbWFyLCBTWkEgLSBBbGwgVGhlIFN0YXJzAA5LZW5kcmljayBMYW1hcgAAAAAAA53IAAtHZkNxTXYtLW5jQQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PUdmQ3FNdi0tbmNBAQAwaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9HZkNxTXYtLW5jQS9tcWRlZmF1bHQuanBnAAAHeW91dHViZQAAAAAAAAAA',\n" +
  '    info: {\n' +
  "      identifier: 'GfCqMv--ncA',\n" +
  '      isSeekable: true,\n' +
  "      author: 'Kendrick Lamar',\n" +
  '      length: 237000,\n' +
  '      isStream: false,\n' +
  '      position: 0,\n' +
  "      title: 'Kendrick Lamar, SZA - All The Stars',\n" +
  "      uri: 'https://www.youtube.com/watch?v=GfCqMv--ncA',\n" +
  "      sourceName: 'youtube',\n" +
  "      artworkUrl: 'https://i.ytimg.com/vi/GfCqMv--ncA/mqdefault.jpg',\n" +
  '      isrc: null\n' +
  '    },\n' +
  "    pluginInfo: { save_uri: 'https://www.youtube.com/watch?v=GfCqMv--ncA' },\n" +
  '    userData: {}\n' +
  '  },\n' +
  '  exception: {\n' +
  "    message: 'Something broke when playing the track.',\n" +
  "    severity: 'fault',\n" +
  "    cause: 'java.lang.IllegalStateException: Must find action functions from script: /s/player/f8f53e1a/player_ias.vflset/bn_BD/base.js'\n" +
```
lavalink logs

```
t:"*/*", user-agent:"Discord/Bot/rainlink/[object Object] (https://github.com/RainyXeon/Rainlink)", Content-Type:"application/json;charset=UTF-8"]
2024-12-14T20:01:45.282Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/3djz6asst4zr23fi/players/1315007919527559300?noReplace=false, client=10.10.10.10, headers=[sec-fetch-mode:"cors", authorization:"youshallnotpass", content-length:"336", accept-language:"*", host:"dh1.ozima.cloud:2212", connection:"keep-alive", accept-encoding:"gzip, deflate", accept:"*/*", user-agent:"Discord/Bot/rainlink/[object Object] (https://github.com/RainyXeon/Rainlink)", Content-Type:"application/json;charset=UTF-8"], payload={"track":{"encoded":"QAAAvwMAI0tlbmRyaWNrIExhbWFyLCBTWkEgLSBBbGwgVGhlIFN0YXJzAA5LZW5kcmljayBMYW1hcgAAAAAAA53IAAtHZkNxTXYtLW5jQQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PUdmQ3FNdi0tbmNBAQAwaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9HZkNxTXYtLW5jQS9tcWRlZmF1bHQuanBnAAAHeW91dHViZQAAAAAAAAAA","length":237000},"replaceCurrent":false,"volume":100}
2024-12-14T20:01:45.841Z ERROR 27 --- [Lavalink] [back-1-thread-1] d.l.y.cipher.SignatureCipherManager      : Problematic YouTube player script /s/player/f8f53e1a/player_ias.vflset/bn_BD/base.js detected (issue detected with script: no actions match). Dumped to /tmp/lavaplayer-yt-player-script3603784922776290863.js (Source version: 1.8.3)
2024-12-14T20:01:45.842Z ERROR 27 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of GfCqMv--ncA

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/f8f53e1a/player_ias.vflset/bn_BD/base.js
        at dev.lavalink.youtube.cipher.SignatureCipherManager.extractFromScript(SignatureCipherManager.java:236) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.cipher.SignatureCipherManager.getCipherScript(SignatureCipherManager.java:196) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:86) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:193) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:119) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[youtube-plugin-1.8.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        ... 4 common frames omitted
        Suppressed: dev.lavalink.youtube.ClientInformation: 
  yts.version: 1.8.3
  client.identifier: ANDROID_MUSIC
  client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}

2024-12-14T20:01:46.254Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/3djz6asst4zr23fi/players/1315007919527559300, client=10.10.10.10, headers=[sec-fetch-mode:"cors", authorization:"youshallnotpass", accept-language:"*", host:"dh1.ozima.cloud:2212", connection:"keep-alive", accept-encoding:"gzip, deflate", accept:"*/*", user-agent:"Discord/Bot/rainlink/[object Object] (https://github.com/RainyXeon/Rainlink)", Content-Type:"application/json;charset=UTF-8"]
2024-12-14T20:01:47.058Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/stats, client=10.10.10.10, headers=[sec-fetch-mode:"cors", authorization:"youshallnotpass", accept-language:"*", host:"dh1.ozima.cloud:2212", connection:"keep-alive", accept-encoding:"gzip, deflate", accept:"*/*", user-agent:"Discord/Bot/rainlink/[object Object] (https://github.com/RainyXeon/Rainlink)", Content-Type:"application/json;charset=UTF-8"]
2024-12-14T20:01:47.538Z  INFO 27 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/3djz6asst4zr23fi/players/1315007919527559300?noReplace=false, client=10.10.10.10, headers=[sec-fetch-mode:"cors", authorization:"youshallnotpass", content-length:"127", accept-language:"*", host:"dh1.ozima.cloud:2212", connection:"keep-alive", accept-encoding:"gzip, deflate", accept:"*/*", user-agent:"Discord/Bot/rainlink/[object Object] (https://github.com/RainyXeon/Rainlink)", Content-Type:"application/json;charset=UTF-8"], payload={"voice":{"token":"7fedc137cd12a58c","endpoint":"india10038.discord.media:443","sessionId":"fe9850f74248a23f8a02fa1cacfb116b"}}
```

### What is your client configuration?

rainlink

**Comment by apex2504** [comment]
> * [x] I am using (and my issue is reproducible on) the latest version of youtube-source.

> Version of youtube-source
1.8.3

You are in fact not using the lastest version of youtube-source.

**Comment by Naiml007** [comment]
> Contributor

> I tried version 1.11.1, but I'm still getting same Error.

**Comment by devoxin** [comment]
Update and post a stacktrace from 1.11.1. We do not accept bug reports for older versions.

**Comment by Naiml007** [comment]
> Update and post a stacktrace from 1.11.1. We do not accept bug reports for older versions.

ok
