### ISSUE TITLE
This video requires login.

### ISSUE THREAD

**Issue by B3ni15** [lavalink-devs/youtube-source#92]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.11.1

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

ytmsearch:Sigma boy

### Code Example

```python
import discord
from discord.ext import commands
import wavelink
from controller.queue_module import add_track, pop_track, set_text_channel
from controller.lang_module import get_translation

class Play(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.slash_command(name="play", description="Play a song from YouTube.")
    async def play(self, ctx: discord.ApplicationContext, search: str):
        if not ctx.author.voice or not ctx.author.voice.channel:
            await ctx.respond(get_translation(ctx.guild.id,"Song_You_must_be_in_vc"), ephemeral=True)
            return

        vc = ctx.guild.voice_client

        if not vc:
            vc = await ctx.author.voice.channel.connect(cls=wavelink.Player)
            await ctx.guild.change_voice_state(channel=ctx.author.voice.channel, self_mute=False, self_deaf=True)
            set_text_channel(ctx.guild.id, ctx.channel)

            print(vc.node)

            if not vc.node:
                await vc.destroy()
                await ctx.respond(get_translation(ctx.guild.id,"Song_No_node_found"), ephemeral=True)
                return

        if ctx.author.voice.channel.id != vc.channel.id:
            await ctx.respond(get_translation(ctx.guild.id,"Song_You_must_be_in_same_vc"), ephemeral=True)
            return

        await ctx.defer()
        initial_msg = await ctx.respond(get_translation(ctx.guild.id,"Song_Searching"))

        try:
            tracks = await wavelink.Playable.search(search)
        except Exception as e:
            embed = discord.Embed(title=get_translation(ctx.guild.id,"Err_searching"), color=discord.Color.red())
            await initial_msg.edit(content=None, embed=embed)
            return

        if not tracks:
            embed = discord.Embed(title=get_translation(ctx.guild.id, "No_Song_Found"), color=discord.Color.red())
            await initial_msg.edit(content=None, embed=embed)
            return

        is_playlist = "playlist" in search.lower()

        if is_playlist:
            for track in tracks:
                add_track(ctx.guild.id, track)

            if not vc.playing:
                embed = discord.Embed(title=f"{get_translation(ctx.guild.id, 'Song_Playing_1')} {tracks[0].title} {get_translation(ctx.guild.id, 'Song_Playing_2')} {tracks.name}", description=f"{get_translation(ctx.guild.id, 'Song_Playing_des_1')} {len(tracks) - 1} {get_translation(ctx.guild.id, 'Song_Playing_des_2')}", color=0x5865F2, timestamp=initial_msg.created_at, url=tracks.url)
                embed.set_thumbnail(url=tracks[0].artwork)
                await vc.play(pop_track(ctx.guild.id))
                await initial_msg.edit(content=None, embed=embed)
            else:
                embed = discord.Embed(title=f"{get_translation(ctx.guild.id, 'Song_Added_Playing_1')} {tracks.name} {get_translation(ctx.guild.id, 'Song_Added_Playing_2')} {len(tracks)} {get_translation(ctx.guild.id, 'Song_Added_Playing_3')}", color=0x5865F2, timestamp=initial_msg.created_at, url=tracks.url)
                embed.set_thumbnail(url=tracks[0].artwork)
                await initial_msg.edit(content=None, embed=embed)
        else:
            add_track(ctx.guild.id, tracks[0])

            if not vc.playing:
                await vc.play(pop_track(ctx.guild.id))
                embed = discord.Embed(title=f"{get_translation(ctx.guild.id, 'Song_Playing_1')} {tracks[0].title}.", color=0x5865F2, timestamp=initial_msg.created_at, url=tracks[0].uri)
                embed.add_field(name=get_translation(ctx.guild.id, "Song_Author"), value=tracks[0].author, inline=True)
                embed.add_field(name=get_translation(ctx.guild.id, "Song_Duration"), value=f"{(tracks[0].length // 1000) // 60}:{(tracks[0].length // 1000) % 60:02}", inline=True)
                embed.add_field(name=get_translation(ctx.guild.id, "Song_requested_by"), value=ctx.author.mention, inline=False)
                embed.set_thumbnail(url=tracks[0].artwork)
                await initial_msg.edit(content=None, embed=embed)
            else:
                embed = discord.Embed(title=f"{get_translation(ctx.guild.id, 'Song_Added_to_queue')} {tracks[0].title} {get_translation(ctx.guild.id, 'Song_Added_to_queue2')}", color=0x5865F2, timestamp=initial_msg.created_at, url=tracks[0].uri)
                embed.add_field(name=get_translation(ctx.guild.id, "Song_Author"), value=tracks[0].author, inline=True)
                embed.add_field(name=get_translation(ctx.guild.id, "Song_Duration"), value=f"{(tracks[0].length // 1000) // 60}:{(tracks[0].length // 1000) % 60:02}", inline=True)
                embed.add_field(name=get_translation(ctx.guild.id, "Song_requested_by"), value=ctx.author.mention, inline=False)
                embed.set_thumbnail(url=tracks[0].artwork)
                await initial_msg.edit(content=None, embed=embed)

def setup(bot):
    bot.add_cog(Play(bot))
```

### Exception and Stacktrace

```bash
2024-12-15T21:51:19.723+01:00  WARN 26 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of HXoahG4iqTs

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video requires login.
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104) ~[youtube-plugin-1.11.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

### What is your client configuration?

MUSIC,ANDROID_VR,WEB,WEBEMBEDDED

**Comment by B3ni15** [comment]
> I tested it with oauth2 and po token, but it returns this for all of them...

**Comment by devoxin** [comment]
OAuth only works with [OAuth-enabled clients](https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#available-clients). Enable OAuth and reconfigure your enabled clients.
