### ISSUE TITLE
Suspicious exception for playback of xxxxxx

### ISSUE THREAD

**Issue by Bu1227** [lavalink-devs/youtube-source#95]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.11.1

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

ytsearch:

### Code Example

N/A

### Exception and Stacktrace

2024-12-19T11:16:54.642-05:00  WARN 26 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of 0rzOykYyXP9Z9VFCh67TNn
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This content isn’t available.
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104) ~[youtube-plugin-1.11.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
        at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:55) ~[lavasrc-plugin-4.3.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

### What is your client configuration?

- MUSIC      - WEB      - WEBEMBEDDED      - TV

**Comment by dazzypark** [comment]
Maybe your account is suspended account. Switch to another account, but soon that account will be suspended too.

**Comment by Bu1227** [comment]
Yes, maybe due to high usage.
I have 4 Google accounts and 4 Lava link nodes. When this error occurred, only some of the nodes/accounts had this exception, and I can't even use those accounts to watch YouTube videos using my browser.
I have tried the solution in #91 , but it doesn't work.

**Comment by Nansess** [comment]
> Yes, maybe due to high usage. I have 4 Google accounts and 4 Lava link nodes. When this error occurred, only some of the nodes/accounts had this exception, and I can't even use those accounts to watch YouTube videos using my browser. I have tried the solution in #91 , but it doesn't work.

means your account is flagged

**Comment by Bu1227** [comment]
Sad :(
I'll try to add more lavalink node and account to balance usage.
