### ISSUE TITLE
Exception when seeking before or immediately after playing a track

### ISSUE THREAD

**Issue by Rapha149** [lavalink-devs/youtube-source#97]
### Basic Troubleshooting

- [X] I have checked for similar issues (open AND closed), and my issue is not a duplicate. (MANDATORY)
- [X] I have checked for pull requests that may already address my issue. (MANDATORY)
- [X] I am using (and my issue is reproducible on) the latest version of youtube-source.
- [X] My issue is reproducible with IPv6 rotation.

### Version of youtube-source

1.11.3

### The search query/queries, URL(s), playlist ID(s)/URL(s) or video ID(s)/URL(s) that triggered the issue

https://youtu.be/CczcMarUoVk

### Code Example

```java
AudioTrack track = ...
AudioPlayer player = ...
track.setPosition(60000);
player.playTrack(track);
```

### Exception and Stacktrace

```
ERROR com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor - Error in playback of CczcMarUoVk
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:159)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:138)
	at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:79)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
	... 4 more
	Suppressed: dev.lavalink.youtube.ClientInformation: 
  yts.version: 1.11.3
  client.identifier: WEB
  client.options: ClientOptions{playback=true, playlistLoading=true, videoLoading=true, searching=true}
```

### What is your client configuration?

The default ones: new Music(), new AndroidVr(), new Web(), new WebEmbedded()

**Comment by Nansess** [comment]
It basically has to do with YouTube's new A/B testing. Googlevideo URLs are now being generated more aggressively. Googlevideo URLs generated without OAuth have stricter limits, especially regarding the IPs that access them. This happens on IPv6 as well, mostly for smaller blocks.

https://github.com/yt-dlp/yt-dlp/issues/11868 (same thing)

**Comment by Rapha149** [comment]
But I don't get why it only happens when I set the position of the track before playing or too quickly afterwards. If I don't set the position it works fine.

**Comment by Nansess** [comment]
Just wait a second, as you mentioned—that worked. This was common in Android clients, which would often fail halfway with a 403 error. However, as I said before, A/B testing of new restrictions on Googlevideo URLs could possibly be one of the reasons.

**Comment by Rapha149** [comment]
Ok, thanks :+1: 
I now implemented that the video will start paused, then after a second I change the position and resume the player, it takes an extra second but it's not so bad :shrug:
